recipe: default.v1

language: ru

pipeline: 
  - name: SpacyNLP
    model: ru_core_news_sm
  - name: SpacyTokenizer
  - name: SpacyFeaturizer

  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: faq 
    # constrain_similarities: true
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: chitchat

  - name: FallbackClassifier
    threshold: 0.7 # порог достоверности намерения
    ambiguity_threshold: 0.1

  - name: "DucklingEntityExtractor"
    url: "http://localhost:8000"    
    dimensions: ["time"]
    locale: "ru_GB"

policies:
- name: MemoizationPolicy
  max_history: 3
- name: RulePolicy
  core_fallback_threshold: 0.4 # достоверность предсказания следующего отклика
  core_fallback_action_name:  action_default_fallback
  enable_fallback_prediction: true
# - name: UnexpecTEDIntentPolicy
#   max_history: 5
#   epochs: 100
- name: TEDPolicy
  max_history: 3
  epochs: 100
  constrain_similarities: true

assistant_id: 20240415-111102-proper-tracking 
